# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='voivodeship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Voivodeship'),
        ),
    ]
